# Generated by Django 5.0.2 on 2024-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
