# Generated by Django 5.0.2 on 2024-03-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_remove_user_id_user_membership_date_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
